### ISSUE TITLE
Chinese text is not properly rendered in scrapes from sketchy

### ISSUE THREAD

**Issue by jwilczek** [Netflix/sketchy#32] opened 2016-03-08 14:37 UTC
When Scumblr finds results on Chinese websites the scrapes are incorrect and show none of the original language text.  All text is replaced with a box, such as &#9633;.

Thank  you,

Josh

**Comment by sbehrens** [comment] 2016-03-08 18:30
Hi Josh,

I found the line that is affecting the scrape:

https://github.com/Netflix/sketchy/blob/32b60b0ea7eb178307c88dd99a469ae8552790e2/sketchy/controllers/tasks.py#L143 - forces UTF-8 encoding and this is where you would need to change it to support other encoding formats.

I'll keep this open as a bug but if you'd like to fix it, feel free to submit a pull request.

**Comment by jwilczek** [comment] 2016-03-08 19:55
Hmmm - it seems like UTF-8 should do it.  I mean, UTF-8 supports Chinese characters, right?  In browsing to the pages that are not working with sketchy, the charset is even specified as utf-8 in the page.  Any other thoughts?

For what it's worth, I've noticed that other languages (Russian, for example) are working fine.

Josh

**Comment by sbehrens** [comment] 2016-03-08 20:16
Hi Josh,

I am not sure, will keep this issue open and try to dig a bit deeper
later.  Does it render the same in Scumblr as it does in Sketchy?

Scott

**Comment by jwilczek** [comment] 2016-03-08 20:37
It appears to render incorrectly in both.  Meaning, if I look at the raw .txt files in sketchy the text is garbage.  If I look at it through Scumblr, I get the boxes.

**Comment by x123** [comment] 2016-08-30 13:13
@jwilczek it could be that you do not have the correct fonts installed on the machine running sketchy. I'm not sure what distro you are on, but there are several that may fix the issue with the characters rendering properly in the image produced by phantomjs. On Debian, you might try these:

`apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-arphic-gbsn00lp fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gkai00mp ttf-bitstream-vera ttf-dejavu ttf-mscorefonts-installer`

Additionally, which version of phantomjs are you using? The stackoverflow link listed below seems to indicate that "There's a fix for Japanese/Chinese/Korean characters in the 1.9.1 release."

Related stackoverflow:
http://stackoverflow.com/questions/15029002/phantomjs-screenshot-font-missing-boxes-rendered-instead

**Comment by x123** [comment] 2016-08-31 11:21
@jwilczek @sbehrens As a followup, I've confirmed that for me, although I am using phantomjs 2.1.1, the issue is present on a stock debian machine (Chinese characters not rendering properly), and with the addition of most of the above listed packages it is resolved. I have created the following pull request to address the issue: #36

**Comment by jwilczek** [comment] 2016-08-31 11:24
@x123 Thanks! I will try your suggestion today and let you know if it works.

**Comment by jwilczek** [comment] 2016-08-31 21:17
@x123 that solved my problem! thank you! ...now I just got to figure out cyrillic fonts. I've been trying to take the same approach of locating the proper font packet, but have not been successful yet.

**Comment by x123** [comment] 2016-08-31 22:06
@jwilczek you might try the following, and run an fc-cache -fv after installation. Let me know if it does work, would like to include in my fork and submit an upstream pull request similar to #36 if so.

```
fonts-oldstandard - smart font with wide range of Latin, Greek and Cyrillic characters
fonts-sil-charis - smart Unicode font family for Roman or Cyrillic-based writing systems
fonts-sil-doulos - smart Unicode font for Latin and Cyrillic scripts
fonts-uralic - Truetype fonts for Cyrillic-based Uralic languages
```

**Comment by jwilczek** [comment] 2016-09-01 12:32
@x123 no luck installing those fonts. As I look through my results, it appears most cyrillic text was working before installing those fonts. It's possible the issues with Cyrillic text are site specific. Thanks for your help!

**Comment by jwilczek** [comment] 2016-09-01 17:24
@x123 scratch that - those fonts worked for cyrillic as well (I had some other issues unrelated to sketchy)!!!

**Comment by sbehrens** [comment] 2016-09-01 17:48
Thanks @x123 for the help.  Closing this one.

**Closed by sbehrens** 2016-09-01 17:48 UTC
Labels: enhancement, help wanted
